package com.example.nebojsa.twofactsonefake;

public class Game {
    private static String[] easyFacts={"Cleopatra was not Egyptian, she was Greek.",
            "Cleopatra was the last Pharaoh of Egypt.",
            "The Titanic movie broke all previous Box Office records.",
            "Lowest point on land is The Dead Sea, Israel-Jordan, with water surface 411m (1,349 ft) below sea level.",
            "Venus Williams recorded a serve of 205 km/h (127 mph) and became the fastest server in women’s tennis.",
            "Densest population in the world is in Monaco with 14,551 per square km (37,687 per square mile).",
            "The world's highest waterfall is Angel Falls (Venezuela), 980m (3212 ft) high.",
            "Largest country in the world is Russia, with surface of 17,098,240 square km (6,572,560 square miles).",
            "Smallest Country in the world is Vatican City, with surface of 108.7 acres.",
            "Total of 70.9% of the Earth's surface is covered with water.",
            "Total of 29.1% of the Earth's surface is land.",
            "Currently there are over 7 billion people living on Earth.",
            "Almost 2/3 (around 63.4%) of people live in Asia.",
            "Every 5th person on Earth is Chinese.",
            "Average life expectancy in the world is 67.2 years.",
            "On average, women live 6 years longer than men.",
            "Average life span more than doubled from 1900s to 2000s.",
            "First story ever written is the Epic of Gilgamesh, in its Sumerian version predating 2100 BC.",
            "Bible is the world's best selling book of all time.",
            "The largest statue in the world is Mount Rushmore, the heads of 4 US presidents are 18m (60 ft) tall.",
            "2 billion people still cannot read.",
            "11% of people are left handed.",
            "If you try to say the alphabet without moving your lips or tongue every letter will sound the same.",
            "The names of all continents both start and end with the same letter.",
            "Money is the number one thing that couples argue about.",
            "About 90% of the worlds population kisses.",
            "Koalas sleep around 18 hours a day.",
            "All insects have 6 legs.",
            "A strawberry is the only fruit which seeds grow on the outside.",
            "An average person will spend 25 years asleep.",
            "Everyday is a holiday somewhere in the world.",
            "The most commonly forgotten item for travelers is their toothbrush.",
            "Hilton was the first international hotel chain.",
            "Monopoly is the most played board game in the world.",
            "96% of candles sold are purchased by women.",
            "The only animals that purr are cats.",
            "China manufacturers 70% of the worlds toys.",
            "Gold never erodes.",
            "A piece of paper cannot be folded more than 7 times.",
            "The smallest dog is the Chihuahua.",
            "The worlds smallest bird is the 'bee hummingbird' found in Cuba.",
            "DVDs are physically the same size as a CDs but can store 13 times more data.",
            "Soccer is the most followed sport.",
            "Average jogger could have run faster than the first train.",
            "A flea can jump 350 times its body length.",
            "Cucumbers are 96% water.",
            "A jellyfish is 95% water.",
            "Bats are the only mammals that fly.",
            "New York was once called New Amsterdam.",
            "More than 75% of all countries are north of the equator.",
            "The water in the Dead Sea is so salty, it's easier to float than to sink.",
            "Rio de Janeiro translates to river of January.",
            "After petrol, coffee is the largest item bought and sold.",
            "The atomic symbol for iron is Fe.",
            "Sharks can sense a drop of blood from 4km (2.5miles) away.",
            "Mercury is the only metal that is liquid at room temperature.",
            "90% people depend on alarm clocks to wake up.",
            "You can't tickle yourself.",
            "Squirrels can climb trees faster than they can run on the ground.",
            "A blue whale can weigh as much as 30 elephants .",
            "Hippos have skin 3.8cm (1.5in) thick.",
            "The tallest mammal is the giraffe.",
            "The average shower tempreture is 38°C (101°F).",
            "No two spider webs are the same.",
            "Australia is the only country that is also a continent.",
            "Fingernails grow faster than toenails.",
            "Wheat is the world's most widely grown plant.",
            "Laughing lowers levels of stress and strengthens your immune system.",
            "All snakes are carnivorous.",
            "Diamonds are the hardest substance known to man.",
            "Vatican City has the smallest population - of only 800.",
            "Honey is the only food that doesn't spoil.",
            "Newborn dogs are born blind and deaf.",
            "Every piece of plastic ever made still exists.",
            "Women on average say about 3 times more words per day than men.",
            "The lighter was invented before the match.",
            "The most searched tutorial on youtube is 'How to kiss'.",
            "123456 is the most commonly hacked password.",
            "68% of the people suffer from phantom vibration, the feeling that one's phone is vibrating when it's not.",
            "The human body is comprised of 80% water.",
            "Elephants have the longest pregnancy in the animal kingdom at 22 months.",
            "Your tongue is the only muscle in your body that is attached at only one end.",
            "It’s impossible to sneeze with your eyes open.",
            "The city of Venice stands on about 120 small islands.",
            "Negative emotions such as anxiety and depression can weaken your immune system.",
            "The most common name in world is Mohammed."}
            , mediumFacts = {"Albert Einstein failed his first entrance exam to College in 1895.",
            "In 1996 NASA claimed they found life on Mars.",
            "Mankind has sent over 40 space missions to Mars.",
            "There are 3 Robots on Mars right now.",
            "Mars has a mountain 3 times bigger than Mount Everest.",
            "Every so often, Saturn's rings disappear.",
            "Neptune was predicted mathematically before it was seen in 1846.",
            "Tornadoes have been witnessed on every continent except Antarctica.",
            "Jupiter is 2.5 times as massive as all the other planets combined.",
            "Abraham Lincoln was the tallest president, he was 191cm (6\"4') tall.",
            "Spices were as valuable as gold in the 1500’s.",
            "George Washington was the only president to be unanimously elected.",
            "George Washington did not want to be paid to be president.",
            "The Statue of Liberty was first on display in France for 6 months.",
            "A conman named Victor Lustig sold the Eiffel Tower… Twice!",
            "Argentina is the largest Spanish speaking country in the world.",
            "There are 53 cities in India with a population of 1 million or more as of 2011.",
            "Miroslav Klose holds the record for most World Cup goals ever - 16.",
            "The shortest match in the history of tennis lasted only about 20 minutes.",
            "The longest mountain system, Andes, South America, is 8800 km (5470 miles) long.",
            "There are 9.5 times more languages spoken in Asia than in Europe.",
            "Alpha Centauri Bb is the closest star to the Earth, only 4.37 light years away.",
            "The speed of sound in air in normal conditions is 1225 km/h (761.2 mph).",
            "The Universe is 13.73±0.12 billion years old.",
            "The world's longest coral reef	is the Great Barrier Reef (Australia), 2028km (1260 miles) long.",
            "Total surface area of the Earth is 510,066,000 square km (196,069,370 square miles).",
            "Average radius of the Earth is 6,371km (3958 miles).",
            "Asia has bigger surface area than South America, Europe and Australia combined.",
            "China has a bigger population than Europe and Australia combined.",
            "Stonehenge (UK) is 8m (26 ft) tall.",
            "If HIV/AIDS didn't exsist, average life expectancy in  Botswana (Africa) would be 70.7 years instead of 31.6.",
            "Lamborgini Veneno costs $4.5 million.",
            "Picasso could draw before he could walk and his first word was the Spanish word for pencil.",
            "The largest statue in the world is Mount Rushmore, the heads of 4 US presidents are 18m (60 ft) tall.",
            "There are more than a million animal species.",
            "About one third of animals have been driven to extinction as a result of mismanagement and polution by the fast-growing human population.",
            "Adult frogs are carnivorous and will eat just about anything smaller than themselves, including insects, worms and even other frogs.",
            "Greek philosopher Aristotle wrote Meteorologica in 350 BC – it remained the standard textbook on weather for 2,000 years.",
            "August has the highest percentage of births.",
            "The average person falls asleep in 7 minutes.",
            "'Topolino' is the name for Mickey Mouse Italy.",
            "The most commonly used letter in the alphabet is E.",
            "The 3 most common languages in the world are Mandarin Chinese, Spanish and English.",
            "Spiders are not insects.",
            "Coca-Cola originally contained cocaine.",
            "Australia was originally called New Holland.",
            "The average human brain contains around 78% water.",
            "At birth dalmatians are always white.",
            "Hummingbirds are the only bird that can fly backwards.",
            "A duck can't walk without bobbing its head.",
            "Hippos have killed more people in Africa than any other animal.",
            "Elephants ears are used to regulate body temperature.",
            "The word LASER stands for 'Light Amplification by Stimulated Emission of Radiation'.",
            "Cows don't have upper front teeth.",
            "In a deck of cards, the king of hearts is the only king without a moustache.",
            "An octopus pupil is rectangular.",
            "Its physically impossible for pigs to look up at the sky.",
            "42% of men and 25% of women don't wash their hands after using a public toilet.",
            "Nearly 2.1 billion people have social media accounts.",
            "Close to 1.7 billion people have active social media accounts.",
            "There are just over 3 billion active Internet users (45% of the world’s population).",
            "There are nearly 1.4 billion Facebook users.",
            "47% of all Internet users are on Facebook.",
            "70 million photos and videos are uploaded daily on Instagram.",
            "Paper originated from China.",
            "The Great Wall of China is approximately 6,430km (3,995 miles) long.",
            "Hard boiled eggs spin (uncooked or soft boiled don't).",
            "Women blink twice as much as men.",
            "Household dust is made of dead skin cells.",
            "India is home to over 200 million cows.",
            "Madonna and Michael Jackson were both born in 1958.",
            "An egg contains every vitamin except vitamin C.",
            "Owls can't move their eyes from side to side.",
            "Scorpions glow under ultra violet light.",
            "Halley's comet passes the Earth every 76 years (the next time it will return will be 2062).",
            "Porsche also builds tractors.",
            "Buckingham Palace has over 600 rooms.",
            "The most fatal car accidents occur on Saturdays.",
            "The Coca-Cola brand is worth an estimated $74 billion: more than Budweiser, Pepsi, Starbucks and Red Bull combined.",
            "Earth is the only planet not named after a god.",
            "Your mouth produces 1 liter of saliva a day.",
            "During a total solar eclipse the temperature can drop by 6°C (20°F).",
            "Today, there are over 300 cities in the world with a population larger than 1 million.",
            "Women make up 49% of the world's population.",
            "Wine is sold in tinted bottles because it spoils when exposed to light.",
            "Carrots contain 0% fat.",
            "1 billion snails are served in restaurants each year.",
            "In developed countries 27% of food is thrown away.",
            "Cheetah is the fastest land animal in the world, with the top speed of 114km/h (70mph).",
            "Horses sleep standing up.",
            "A snail can sleep for 3 years.",
            "Hippos are born under water.",
            "There are more insects in the world than all other animals combined.",
            "Grasshoppers have white blood.",
            "The hydrochloric acid found in your stomach is strong enough to dissolve a nail.",
            "Minus 40°C is exactly the same temperature as minus 40°F.",
            "Paper money was first used in China.",
            "Oxygen, carbon, hydrogen and nitrogen make up 90% of the human body.",
            "Artificial Christmas trees have outsold real ones every year since 1991.",
            "80% of burglaries are committed by people aged 13-21.",
            "Half of all crimes are committed by people under the age of 18.",
            "The most common disease is tooth decay.",
            "The average person goes to the toilet 6 times a day.",
            "Giraffes has the highest blood pressure of any animal.",
            "Japan is the largest exporter of frog legs.",
            "Women's hearts beat faster than men's.",
            "The only continent without reptiles or snakes is Antarctica.",
            "Butterflies taste with their back feet.",
            "Bees have 4 wings.",
            "The most eaten fruit in America is the banana.",
            "Canada has more lakes than any other country.",
            "90% of all volcanic activity occurs in the ocean.",
            "Trees do not have life expectancies (most can grow indefinitely).",
            "Your blood is 6 times thicker than water.",
            "The most common Spanish surname is Garcia.",
            "The US produces 19% of the world's trash.",
            "53% of women don't leave home without makeup on.",
            "'Fan' is short for 'fanatic'.",
            "The 'black box' that houses an airplane's voice recorder is actually orange .",
            "Camels can drink 94 litres (25 gallons) of water in less than 3 minutes.",
            "Antarctica is 98% ice and 2% barren rock.",
            "Finland has the largest number of islands in the world (over 179,550).",
            "The only thing that can destroy a diamond is intense heat.",
            "The world's first paved streets were laid in Rome in 170 B.C.",
            "Every living thing on the Earth contains carbon.",
            "Dinosaurs lived on Earth for over 165 million years before they became extinct.",
            "2 out of 5 people marry their first love.",
            "The algae found in the world's oceans produces nearly 50% of the world's oxygen.",
            "Chameleons can move their eyes in two directions at the same time.",
            "A chameleon's tongue is twice as long as its body.",
            "England's Stonehenge is over 5,000 years old.",
            "The Eiffel Tower is over 300m (984 ft) tall.",
            "52% of Americans drink coffee.",
            "1 plain milk chocolate bar has more protein than a banana.",
            "Between 1931 and 1969 Walt Disney was awarded 35 Oscars.",
            "The first music video shown on MTV was 'Video killed the radio star' by the Buggles.",
            "Europe is the only continent without a desert.",
            "Muscles make 40% of the total body weight of an average person.",
            "The average age at which America's presidents have taken office is 54.",
            "Lions feed once every 3 to 4 days.",
            "An office desk has 400 times more bacteria than a toilet.",
            "Looking from space, the brightest man made place is Las Vegas.",
            "There are 2 credit cards for every person in the US.",
            "The human body creates 2,500,000 new red blood cells every second.",
            "The only letter which doesn't appear in the Periodic Table is 'j'.",
            "Hydrogen is the most abundant element in the Universe (75%).",
            "Europe has more countries than Asia.",
            "South America is a continent with the least number of countries: 12.",
            "China has the most neighboring countries: 14.",
            "India will surpass China to become world's most populous nation around 2028.",
            "There are more Hindi than Spanish language speakers in the world.",
            "In 1977, 3 men attempted to steal Elvis Presley's remains for ransom.",
            "Snakes use their tongues to smell.",
            "The word 'set' has over 100 definitions.",
            "The cost of college in the U.S. went up 500% from 1985 to 2013.",
            "The fork came to Italy before any other European country because of pasta.",
            "You can see underwater sea life, coral reefs and wrecks using Google Maps.",
            "Polar bears are nearly invisible under infrared photography.",
            "Your stomach has to produce a new layer of mucus every two weeks or it will digest itself.",
            "Chewing gum while peeling onions will keep you from crying.",
            "Because metal was scarce, the Oscars given out during World War II were made of wood.",
            "There are no words in the dictionary that rhyme with orange, purple and silver.",
            "Morgan Freeman didn't appear in a movie until the age of 34.",
            "Charlie Chaplin once lost in a Charlie Chaplin look-alike contest.",
            "In Japanese, there are at least 20 different ways to say 'sorry'.",
            "The movie 'Titanic' won 11 Oscars, but none for acting.",
            "4 out of 5 lies go undetected.",
            "There is no light 9m (30 ft) underwater, so blood appears green.",
            "There are 106 people named Harry Potter.",
            "London has the most billionaires of any city in the world.",
            "Mexico is named after its capital Mexico City, not the other way around.",
            "The founder of Match.com lost his girlfriend to a man she met on Match.com.",
            "There are on average 3 billion Google searches a day.",
            "The color red isn't what causes bulls to attack.",
            "Snakes don't have eyelids.",
            "Lava can flow as fast as a sprinting greyhound.",
            "You can't block Mark Zuckerberg on Facebook.",
            "Recycling 1 ton of paper saves 17 trees.",
            "The first car accident occurred in 1891.",
            "Mosquitoes can mate in midair.",
            "If you have 10$ and no debts you're wealthier than 25% of Americans.",
            "Around 700 photos are uploaded on Instagram every second.",
            "The logo of Alfa Romeo contains a snake eating a man.",
            "475 cigarettes are smoked every second worldwide.",
            "There is a hotel in Sweden built entirely out of ice.",
            "Every year 11,000 Americans injure themselves while trying out bizarre sexual positions.",
            "The strongest muscle in proportion to its size in the human body is the tongue.",
            "All the swans in England are property of the Queen.",
            "A rodent's teeth never stop growing.",
            "More people speak English in China than the United States.",
            "Nerve impulses to and from the brain travel as fast as 274km/h (170mph).",
            "More than 30% of the people in the world have never made or received a telephone call.",
            "90% of bird species are monogamous.",
            "Your nose and ears never stop growing.",
            "Bees have 5 eyes.",
            "Half of all bank robberies take place on a Friday.",
            "Switzerland is the only country with a square flag.",
            "Hair is made from the same substance as fingernails.",
            "Koalas almost never need to drink water.",
            "'You' is the second most spoken English word.",
            "Coca-Cola would be green if coloring wasn’t added to it.",
            "Only one in two billion people will live to be 116 or older.",
            "All snow crystals are hexagonal.",
            "A Czech man holds the record for drinking one liter of beer in 4.11 seconds.",
            "Some species of bamboo can grow up to 90 cm (35 inches) in a day.",
            "A snail takes 33 hours to crawl 1 mile (1,6km).",
            "More people are afraid of spiders than death.",
            "The Australian $5 to $100 notes are made of plastic.",
            "There are no clocks in Las Vegas gambling casinos.",
            "The Black Widow spider eats her mate during or after sex.",
            "The average person spends 6 months of their life sitting at red lights.",
            "Caesar salad has nothing to do with any of the Caesars.",
            "There is enough iron in a human body to make one small nail.",
            "A snail can crawl across a razor blade without getting injured.",
            "Carnivorous animals will not eat another animal that has been hit by a lightning strike.",
            "Until 1965, driving was done on the left-hand side on roads in Sweden.",
            "Between 1912 and 1948, art competitions were a part of the Olympics.",
            "Over 4,000 Chinese children are named ‘Olympic Games’.",
            "World's tallest building is Burj Khalifa, Dubai, 163 stories or 828m (2,717 ft) tall.",
            "12% of sleepers dream in black and white.",
            "There may be no sound in space, but it does have a distinct smell.",
            "The most shoplifted food item in the U.S. is candy.",
            "The world’s shortest scheduled flight lasts 47 seconds." }
            , hardFacts = {"The Earth generates $72 Trillion of goods and services each year.",
            "The center of the Earth, at 5,750°C (10,380 °F), is as hot as the Sun.",
            "When the Earth was formed, a day was only 5.5 hours long.",
            "Albert Einstein read Euclid and Kant when he Was 10 years old.",
            "Abert Einstein convinced FDR to build the atomic bomb.",
            "Uranus has winds that exceed speeds of 800 kilometers (500 miles) per hour.",
            "Saturn has over 100 moons and moonlets.",
            "The most valuable item on the Titanic was a $100,000 painting.",
            "The Eiffel Tower was supposed to be torn down in 1919.",
            "Fastest MMA knockout of all time is 2 seconds.",
            "The most red cards in a soccer game is 20.",
            "Highest PPG (Points Per Game) in NBA history in one season is 50.36, set by Wilt Chamberlain.",
            "Highest PPG (Points Per Game) in NBA history in the whole career is 30.12, set by Michal Jordan.",
            "The longest set in a tennis match ever was finished 70-68 in games.",
            "Coldest region (excluding Antarctica) on Earth is Verkhoyansk in Siberia, with temperatures of -68 ºC (-90 ºF).",
            "Fastest temperature rise recoreded is 27 ºC (49 ºF) in 2 minutes, Spearfish, South Dakota.",
            "Fastest temperature drop ever recorded is 27 ºC (49 ºF) in 15 minutes, Rapid City, South Dakota.",
            "Fastest wind speed ever recorded was 484±32 km/h (301±20 mph),  in a tornado near Oklahoma City.",
            "In Papua-New Guinea  there are an estimated 832 languages spoken by a population of around 3.9 million.",
            "Longest lightning bolt ever measured was 190 km (120 miles) long.",
            "Highest capital city is La Paz (Bolivia), 3,632m (11,916 ft) above sea-level.",
            "The speed of sound in Iron is 18,468 km/h (11,475 mph).",
            "The lowest point underground ever reached was 12,262 metres (40,230 ft).",
            "The earth orbits around the Sun at  107,320 km/h (66,700 mph).",
            "Average Japanese person lives 31,025 days.",
            "In classical Greece, average life span was only 28 years.",
            "Today humans in Swaziland (Africa) have an average life span of 32 years.",
            "Shishi Middle School, China , is the world's oldest school, opened in 143 BC.",
            "The Gutenberg Bible was the first major book printed in the West with movable metal type.",
            "Most expensive car ever sold is 1962 Ferrari 250 GTO, at the price of $52 million.",
            "The name \"Google\" originated from a misspelling of \"googol\", which represents a number 10 to the 100 power (1 followed by 100 zeros).",
            "Google's corporate headquarters is called Googleplex, named after a number Googolplex.",
            "The first history book, the Great Universal History, was published by Rashid-Eddin of Persia in 1311.",
            "The first novel, called The story of Genji, was written in 1007 by Japanese noble woman, Murasaki Shikibu.",
            "The oldest surviving daily newspaper is the Wiener Zeitung of Austria. It was first printed in 1703.",
            "Chinese printed from movable type in 1040 but later discarded the method.",
            "Ernest Vincent Wright’s 1939 novel Gadsby has 50,110 words, none of which contains the letter \"e\".",
            "The shortest stage play is Samuel Beckett’s \"Breath\" – 35 seconds of screams and heavy breathing.",
            "The Library of Congress, the largest library in the world, stores 18 million books on approximately 850km (530 miles) of bookshelves.",
            "The first colour photograph was made in 1861, and it was a photo of a tartan ribbon.",
            "There are 73,000 kinds of spiders.",
            "An ostrich's eye is bigger than it's brain.",
            "Lemons contain more sugar than strawberries.",
            "85% of plant life is found in the ocean.",
            "The flag of Libya is unlike any other being a solid green color.",
            "Goldfish can see both infrared and ultraviolet light.",
            "You burn more calories eating celery than it contains (the more you eat the thinner you become).",
            "The longest street in the world is Yonge street in Toronto, Canada, measuring 1,896 km (1,178 miles).",
            "A giraffe's tounge is 53cm (21 inches) long.",
            "The sentence \"the quick brown fox jumps over the lazy dog\" uses every letter in the English alphabet.",
            "All the blinking in one day equates to having your eyes closed for 30 minutes.",
            "Lightning strikes the Earth 6,000 times every minute.",
            "Fire usually moves faster uphill than downhill.",
            "It's possible to lead a cow up stairs but not down.",
            "Frogs can't swallow with their eyes open.",
            "Your tongue is the fastest healing part of your body.",
            "Frogs don't drink (they absorb water through their skin).",
            "Dragonflies have 6 legs but can't walk.",
            "Pop corn was invented by the Aztec Indians.",
            "Bats always turn left when exiting a cave.",
            "The oldest word in the English language is 'town'.",
            "The average golf ball has 336 dimples.",
            "3.65 billion mobile users have access to the internet via smartphones and tablets.",
            "Direct uploads of user videos to Facebook now exceed YouTube.",
            "600 million users are on Whatsapp.",
            "Social networks will earn $8.3 billion from advertising in 2015.",
            "Tree hugging is forbidden in China.",
            "All of the clocks in the movie 'Pulp Fiction' are fixed to 4:20.",
            "The human body of a 70 kg person contains 0.2mg of gold.",
            "You are more likely to be killed by a champagne cork than by a poisonous spider.",
            "A crocodile can't stick out its tongue.",
            "Only female mosquitoes bite.",
            "Scotland has the most redheads.",
            "India has the most post offices than any other country (over 100,000).",
            "The Taj Mahal in India is made entirely out of marble.",
            "Every single possible 3 character .com domain has been registered.",
            "The word 'testify' derived from a time when men were required to swear on their testicles.",
            "The word typewriter is the longest word that can be typed using only the top row of a keyboard.",
            "Ants stretch when they wake up in the morning.",
            "The longest possible eclipse of the Sun is 7.31 minutes.",
            "Mars appears red because it's covered in rust.",
            "Tennis was originally played with bare hands.",
            "Hawaii was originally called the Sandwich Islands.",
            "Peru has more pyramids than Egypt.",
            "You're more likely to die from falling coconuts than from shark attacks.",
            "Over 2,500 left handed people a year are killed from using right handed products.",
            "An iguana can stay under water for 28 minutes.",
            "The oldest known vegetable is the pea.",
            "The word 'rhythm' is the longest word without a vowel.",
            "Human thigh bones are stronger than concrete.",
            "More people are killed from bees than snakes.",
            "If your DNA was stretched out it would reach the moon 6,000 times.",
            "A dolphin's top speed is 60km/h (37mph).",
            "A shark's top speed is 70km/h (44mph).",
            "There are 70 million sheep in New Zealand (with 4 million people).",
            "African elephants only have 4 teeth.",
            "African elephant's tooth weighs 5kg (11 lbs).",
            "MasterCard was originally called MasterCharge.",
            "The rarest type of diamond is green.",
            "Men are stuck by lightning 7 times more than women.",
            "Plastic bottles were first used for soft drinks in 1970.",
            "The $ sign was introduced in 1788.",
            "In some circumstances, warmer water can freeze faster than colder water (The Mpemba Effect).",
            "More people die from vending machines than from shark attacks.",
            "Crocodiles are color blind.",
            "Bananas grow pointing upwards.",
            "Camels are born without humps.",
            "Crocodiles swallow rocks to help them dive deeper.",
            "Bull's can run faster uphill than down.",
            "There is 200 times more gold in the world's oceans than what has been mined.",
            "Brazil got its name from the Brazilian nut (not the other way around).",
            "New York has 920km (571miles) of shoreline.",
            "The Dead Sea is actually an inland lake.",
            "The subject of the first printed book in England was chess.",
            "The yo-yo was originally used as a weapon for hunting in the Philippines.",
            "An average person blinks 25,000 a day.",
            "You have fewer muscles than a caterpillar.",
            "The first metered taxi was introduced in 1907.",
            "The Chinese used fingerprints as a method of identification as far back as 700 AD.",
            "The revolving door was invented in 1888.",
            "Cars were first started with ignition keys in 1949.",
            "To crack a whip the tip must be travelling faster than the speed of sound.",
            "There is enough petrol in a full tank of a Jumbo Jet to drive the average car 4 times around the world.",
            "Light is electro magnetic radiation.",
            "Most birds eat twice their body weight each day.",
            "The bones of a pigeon weigh less than its feathers.",
            "The cheetah is the only cat that can't retract it's claws.",
            "Dolphins can hear underwater sounds from 24km (15miles) away.",
            "Flamingos can only eat when their heads are upside down.",
            "Leonardo Da Vinci invented scissors.",
            "The US shreds 7,000 tons of worn out currency each year.",
            "There are 1,929,770,126,028,800 different color combinations on a Rubik's Cube.",
            "The average person will consume 100 tons of food in their lifetime.",
            "The average person will consume 45,400 liters (12,000 gallons) of water in their lifetime.",
            "32% of all land in the U.S. is owned by the government.",
            "1 out of every 8 letters written is an 'e'.",
            "You can buy square watermelons in Japan (developed to stack better in supermarkets).",
            "Everyday, more money is printed for Monopoly sets than for the U.S. Treasury.",
            "Wearing headphones for just an hour will increase the bacteria in your ear by 700 times.",
            "Shakespeare invented the words 'assassination' and 'bump'.",
            "In the 17th century the value of number Pi was known to 35 decimal places (today to 1.2411 trillion).",
            "Your foot is the most common body part bitten by insects.",
            "The Sun is 330,330 times larger than the Earth.",
            "Every year the Sun loses 360 million tons.",
            "The first product to have a bar code was Wrigley's gum.",
            "Your right lung takes in more air than your left.",
            "More people are killed by hippos than by lions, elephants and water buffalos combined.",
            "Snakes can't blink.",
            "Bulletproof vests, fire escapes, windshield wipers, and laser printers were all all invented by women.",
            "Bottle nosed whales can dive to a depth of 915 metres (3,000feet) in 2 minutes.",
            "Flamingos can live up to 80 years.",
            "You can tell the sex of a horse by its teeth.",
            "Sharks never stop moving, even when they sleep or rest.",
            "Most cows produce more milk when they listen to music.",
            "A blue whale can go up to 6 months without eating.",
            "House cats have 18 claws.",
            "Shrimps are all born male but slowly grow into females.",
            "Fleas can accelerate 50 times faster than a space shuttle.",
            "Spiders have transparent blood.",
            "Mosquitoes prefer children to adults and blondes to brunettes.",
            "Only 4 out of 20,000 species of bees produce honey.",
            "60 cows can produce a ton of milk each day.",
            "Spain's largest source of income is from tourism.",
            "Before 1863 the postal service in the US was free.",
            "The elevator was invented in 1850.",
            "The first toothbrush was invented in 1498.",
            "Every year over 98% of atoms in your body are replaced.",
            "The average person swallows 295 times during a meal.",
            "On average 22% of all restaurant meals include potato chips.",
            "59% of people say that they're average looking.",
            "The number 1 reason why people purchase a mobile phone is for safety.",
            "Women are 4 times more likely to shop lift than men.",
            "The Earth experiences over 50,000 earthquakes a year.",
            "The first James Bond movie was called 'Dr. No'.",
            "The first crossword puzzle appeared in 1913.",
            "Jellyfish don't have a brain.",
            "45% of Americans don't know that the Sun is a star.",
            "Ferrets sleep between 18-20 hours a day.",
            "A violin contains over 70 separate pieces of wood.",
            "The average person has over 1,460 dreams a year.",
            "Rhinoceros have 3 toes on each foot.",
            "Camels have 3 eyelids to protect themselves from blowing sand.",
            "Most dinosaurs lived to be more than 100 years old.",
            "An ostrich can outrun a horse.",
            "The average cow produces 40 glasses of milk a day.",
            "The greyhound is the fastest dog and can reach speeds of up to 72km/h (45mph).",
            "The fastest fish in the sea is the swordfish and can reach up to speeds of 108km/h (68mph).",
            "An arrow frog has enough poison to kill over 2,200 people.",
            "A baby giraffe is 1.8m (6ft) tall upon birth.",
            "A bear in hibernation loses up to 25% of its body weight.",
            "A camel can shut its nostrils during a desert sandstorm.",
            "The spikes of a newborn hedgehog begin to appear within 24 hours.",
            "93% of households in Denmark consume wine (the highest % in the world).",
            "More people are allergic to cows' milk than any other food.",
            "Employees in Vatican pay no income tax.",
            "The first city to mint its own gold coins was Florence, Italy in 1252.",
            "The national anthems of Japan, Jordan, and San Marino each have only 4 lines.",
            "All the planets in our solar system could fit inside Jupiter.",
            "Natural gas has no smell (the odor is artificially added so that people are able to identify leaks).",
            "It was once illegal to slam your car door in Switzerland.",
            "Jellyfish have been on Earth for over 650 million years.",
            "Sharks have been on Earth for over 400 million years.",
            "The game of Tug-of-war was an Olympic sport from 1900-1920.",
            "A woodpecker can peck 20 times a second.",
            "The Eiffel Tower is repainted every 7 years.",
            "Worker ants may live up to 7 years .",
            "MTV (Music Television) made its debut in 1981.",
            "The first full length animated film was released by Disney Studios in 1937 (it was 'Snow White and the seven dwarves').",
            "The hamburger was invented in 1900.",
            "Hawaii officially became apart of the US in 1900.",
            "Humans shed and regrow outer skin cells every 27 days (almost 1,000 new skins in a lifetime).",
            "The human body has over 600 muscles.",
            "The vocabulary of the average person is between 5,000 to 6,000 words.",
            "Flushable toilets were in use in ancient Rome.",
            "The first credit card was a Diner's Club card issued in 1950.",
            "The average person walks the equivalent of twice around the world in a lifetime.",
            "The surface area of your lungs is roughly the same size as a tennis court.",
            "The world's most expensive spice is saffron.",
            "Albert Einstein never knew how to drive a car.",
            "The original name of Bank of America was Bank of Italy.",
            "The winter of 1932 was so cold that Niagara Falls froze over completely.",
            "An average person produces enough saliva to fill 2 swimming pools during their lifetime.",
            "Cheetahs can accelerate from 0 to 70 km/h (43mph) in 3 seconds.",
            "Tokyo is the largest metro area on Earth with a population of 35.6 million.",
            "The first US President to live in the White House was John Adams (the 2nd President of the USA).",
            "A city in Texas renamed itself to \"DISH, Texas\" in order to receive free Dish Satellite service for 10 years.",
            "Anne Frank wrote most of her diary in the form of letters to a person named 'Kitty'.",
            "Before compasses, Vikings navigated the ocean using birds, whales, celestial bodies, chants and rhymes.",
            "American astronauts have been able to vote in elections from space since 1997.",
            "Vincent Van Gogh's last words were 'The sadness will last forever'.",
            "The Emperor of Japan is the only remaining monarch in the world reigning under the title of 'Emperor'.",
            "On average, 12 newborns will be given to the wrong parents daily.",
            "The Hercules beetle can lift up to 85 times its own weight.",
            "Nintendo was founded in 1889 as a playing-card company.",
            "Mobile Phone Throwing is an official sport in Finland.",
            "It is estimated that it would take 400 billion trees to print out the Internet.",
            "French was the official language of England for almost 300 years.",
            "A woman named Erika La Tour Eiffel married the Eiffel tower in 2007.",
            "There are at least 97 people named LOL in the U.S.",
            "Russia has larger surface area than Pluto.",
            "The Amazon river once flowed in the opposite direction, from east to west.",
            "Cows emit more methane than the oil industry.",
            "There is a Rubik's cube made for blind people. It's called the Braille cube.",
            "Despite the global warming, we're still technically in an ice age.",
            "'Tom and Jerry' was originally called 'Jasper and Jinx'.",
            "Scorpion venom is the most expensive liquid on Earth - 39million dollars per galon.",
            "75% of cars that Rolls-Royce has ever produced are still on the road today.",
            "In Italy, it's illegal to insult a man by saying he has 'no balls'.",
            "Samsung is also a full-time weapons manufacturer.",
            "Your ribs move about 5 million times a year, everytime you breathe.",
            "Golf courses cover 4% of North America.",
            "Until 1994, world maps and globes sold in Albania only had Albania on them.",
            "The town of Calma, Chile in the Atacama Desert has never had rain.",
            "98% of Japanese are cremated.",
            "Earthworms have 5 hearts.",
            "Despite a population of over a billion, China has only about 200 family names.",
            "During it’s lifetime an oyster changes its sex from male to female and back several times.",
            "Ketchup was sold in the 1830s as medicine.",
            "Nepal is the only country that doesn’t have a rectangular flag.",
            "In France, there’s a place called Y.",
            "In ancient Rome, when a man testified in court he would swear on his testicles.",
            "Termites have been known to eat food twice as fast when heavy metal music is playing.",
            "Pig is the only animal besides human that can get sunburns.",
            "The world's youngest parents were 8 and 9 and lived in China in 1910.",
            "Mark Twain didn't graduate from elementary school.",
            "Of all the people aged 65+ that have ever lived, 50% are alive right now.",
            "It is forbidden for aircraft an to fly over the Taj Mahal.",
            "In 1984, a Canadian farmer began renting advertising space on his cows.",
            "A duck’s quack doesn’t echo, and no one knows why.",
            "Jet lag was once called boat lag, before there were jets.",
            "In 10 minutes, a hurricane releases more energy than all the world’s nuclear weapons combined.",
            "Elephants only sleep for two hours a day.",
            "In 400 BC, the Greek city of Sparta had 25,000 citizens and 500,000 slaves.",
            "The February of 1865 is the only month in recorded history not to have a full moon.",
            "People photocopying their buttocks are the cause of 23% of all photocopier faults worldwide.",
            "Peanuts are one of the ingredients of dynamite.",
            "Dragonflies are capable of flying 96km/h (60mph).",
            "At birth, a panda is smaller than a mouse.",
            "A rhinoceros’ horn is made of compacted hair.",
            "Sweden has the least number of murders annually.",
            "Al Capone’s business card said he was a used furniture dealer.",
            "California has issued 6 drivers licenses to people named 'Jesus Christ'.",
            "Icelanders consume more Coca-Cola per capita than any other nation.",
            "Dueling is legal in Paraguay as long as both parties are registered blood donors.",
            "A bull can inseminate 300 cows from one single ejaculation.",
            "The name Jeep came from the abbreviation used in the army - 'G.P.' for ‘General Purpose’ vehicle.",
            "Michael Jordan is the most recognized face in the world, more than the pope himself.",
            "The country code for Russia is 007.",
            "One-fourth of the world’s population lives on less than $200 a year.",
            "90% of all species that have become extinct have been birds.",
            "A pig’s orgasm lasts for 30 minutes.",
            "When Heinz ketchup leaves the bottle, it travels at a rate of 25 miles per year.",
            "Michael Jordan makes more money from NIKE annually than all of the NIKE factory workers in Malaysia combined.",
            "Diamonds were first mined in India over 4,000 years ago.",
            "Money isn't made out of paper, it's made out of linen.",
            "A full-grown bear can run as fast as a horse.",
            "The fingerprints of koala bears are virtually indistinguishable from those of humans.",
            "You can hold the mouth of an alligator shut with two fingers.",
            "A day on Mercury is longer than its year.",
            "All Vietnamese share the same birthday.",
            "It’s possible to buy canned fresh air in China.",
            "A government committee in Iceland prevents parents from giving babies names it deems too weird.",
            "The best man’s original purpose was to serve as an accomplice in case the bride needed to be kidnapped from disapproving parents.",
            "In 2006, an Australian man tried to sell New Zealand on eBay. The price rose to $3,000 before eBay shut it down.",
            "The first registered domain name was registered on March 15th, 1985.",
            "Entomology is the science that studies insects."}
            ;
    private static String[] easyFakes = {"It took 12 years for the Titanic wreck to be found.",
            "Europe is the smallest continent with the surface of 10,180,000 square kilometres (3,930,000 square miles).",
            "Mount Everest Himalayan Mountains, is the highest mountaint on Earth - 13,524m (44,370 feet).",
            "Indian Ocean is the smallest ocean by surface.",
            "Currently there are over 11 billion people living on Earth.",
            "A Song of Ice and Fire, first volume of the series Game of Thrones, is the most selling book of all time.",
            "Japan is the only country with a circular flag.",
            "The smallest bones in the human body are found in your toes.",
            "The largest organ in your body is the liver.",
            "French fries were actually invented in France.",
            "Ostriches bury their heads in sand to hide from predators.",
            "Hummingbirds walk really slowly.",
            "Diamond is the 3rd hardest natural substance.",
            "The opposite sides of a dice always adds up to 8.",
            "Female lions complete around 40% of the hunting in their herd.",
            "America's top selling ice cream flavour is chocolate.",
            "The average hen lays 355 eggs a year.",
            "The average person laughs 3 times a day.",
            "You begin to feel thirsty when your body losses 7-8% of water.",
            "Basketball is the most popular sport on Earth.",
            "You're more likely to win the lottery than to be struck by lightning.",
            "Sir Isaac Newton was 58 when he discovered the law of gravity.",
            "The lie detector was invented in 1991.",
            "The longest time a person has been in a coma is 3 years.",
            "Letters on a mobile keyboard on number 6 are 'DEF'.",
            "A standard 747 jumbo jet has 960 seats.",
            "Crocodiles have the same sets of teeth from birth to death.",
            "80% of all people hit by lightning are women.",
            "Ants can lift up to 6 times their own weight.",
            "There are exactly 1000 bytes in a kilobyte.",
            "It takes 17 muscles to frown and 43 to smile.",
            "The average life span of a mosquito is 6 months.",
            "A soap bubble is roughly the same thickness as the average human hair.",
            "There are 23 people registered living in Antarctica (in 2014).",
            "74.2% of the solar system mass is concentrated in the Sun.",
            "There are now 1.6 billion cell-phones on the planet.",
            "Russia currently has 5 time zones.",
            "Elephant is the only animal that cannot jump.",
            "73% of divorces begin with a marriage.",
            "In the last 3,500 years, there have been approximately 1200 years of peace throughout the civilized world.",
            "Lightning never strikes the same place twice.",
            "People thought the world was flat before Columbus.",
            "The capital of Australia is Sydney.",
            "Every 45 seconds a baby is born somewhere in the world." }
            , mediumFakes = {"Saturn is the only planet with rings in our solar system.",
            "Cleopatra became Pharaoh when she was only 12 years old.",
            "The Eiffel Tower was the World’s tallest structure for 2 years.",
            "Over 1 billion people have visited the Eiffel Tower.",
            "New York city has over 24.2 million citizens by the 2010 US Census.",
            "United States has 26 cities with a population of 1 million or more.",
            "The longest tennis match ever lasted 28 hours and 22minutes, played in 3 days.",
            "Deepest place in the Ocean is near the Island of Mariana Trench, Philippines, 29,876m (98,018 feet).",
            "Highest temperature recorded on Antarctica was -11.1ºC (12.2 ºF).",
            "Light year is equal to 365 regular years.",
            "Sahara desert is the same size as the whole Europe.",
            "Average circumference of the Earth is 24,100km (15,000 miles).",
            "Most expensive luxury car, 2005 Maybach Exelero, costs $2.6 million.",
            "Goliath frog, the largest frog can grow up to 72 cm in length, and weigh up to 9.25 kg.",
            "The Hawaiian alphabet has 24 letters.",
            "The flag of Ukraine is red and blue.",
            "There are active volcanoes on each continent.",
            "1/2 of your bones are in your feet.",
            "You share your birthday with approximately 3.6 million people.",
            "A crocodile can touch his eyelids with his tongue.",
            "The safest car color is black.",
            "Cats can move their jaw in all directions.",
            "Venetian blinds were invented in Venice, Italy.",
            "The Amazon rainforest produces 75% of the world's oxygen supply.",
            "750 million Facebook likes are generated daily.",
            "There are on average 100 million tweets per day.",
            "Camel can last longest without water out of all the animals.",
            "Bill Gates began programming computers at the of age 18.",
            "You take around 7,500 breaths everyday.",
            "Your forearm is twice as long as your foot.",
            "The Eiffel Tower has no steps, only way to get to the top is by elevator.",
            "New York was never the capital of the United States.",
            "All your taste buds are in your tongue.",
            "The first train reached a top speed of only 24 km/h (15 mph).",
            "A banana contains 35% water.",
            "Whales can swim almost twice as fast backwards.",
            "Saudi Arabia is the 13th largest country on Earth and has only 3 rivers.",
            "It took Leonardo Da Vinci 10 months to paint Mona Lisa.",
            "Italy and France produce over 89.7% of all wine.",
            "The first taxi service began in New York in 1878.",
            "Pandas spend 5 hours a day eating bamboo.",
            "There are over 600 different types of apples.",
            "The coffee originated from Brazil.",
            "The word 'karate' means 'defense' in Japanese.",
            "Sea water is approximately 0.3% salt.",
            "Asia is the continent with most countries: 44.",
            "There are more English than Chinese language speakers in the world.",
            "Babies are born on their predicted due date only 29% of the time.",
            "Over 90% of the Sahara desert is covered in sand.",
            "The longest kiss ever recorded lasted 14h 35min.",
            "It takes 45.5 seconds for light to get from the Sun to Earth.",
            "An average human loses about 20 head hairs per day.",
            "In the last 4000 years 12 new animals have been domesticated.",
            "85% of McDonald’s profits come from the sales of Happy Meals.",
            "The average person spends about 4 months on the phone in a lifetime.",
            "The shortest war in history was between Zanzibar and England in 1896 - it lasted 45 hours.",
            "Hair and fingernails continue to grow after death.",
            "Mother birds will abandon their babies if a human touches them.",
            "Human blood turns blue when deoxygenated.",
            "It takes 7 months to digest chewing gum.",
            "Sunflowers track the sun across the sky.",
            "If you shave your legs, your hair will grow back thicker.",
            "Frankenstein was the name of the monster in Mary Shelley's book."}
            , hardFakes = {"The first solar power station was built in 1712.",
            "Saturn is 10 times more massive than Earth.",
            "Neptune has two Moons, Triton and Proteus.",
            "There was a tornado 40 kilometeres (25 miles) wide in Nebraska in 2004.",
            "Jupiter is 136 times the volume of Earth.",
            "Messi holds the record for scoring most goals in a calendar year - 91.",
            "L.A. Lakers hold the record for most consecutive NBA titles - 14.",
            "Michael Jordan holds the NBA single-game scoring record - 137 points.",
            "Beijing is the biggest city in China with over 19 million people.",
            "There are 89 cities in China with a population over 1 million as of 2011.",
            "Tennis originated in France in 18th century.",
            "Most snow in one month in North America was recorded when 490.6 cm (193 inches) of snow fell in Tamarack, California.",
            "Deepest canyon in the world is the Grand Canyon in Colorado, with the depth of 1.6km (1 mile).",
            "Parsec is used to refer to the speed of the sound.",
            "The speed of sound in diamond is 1,846 km/h (1,147 mph).",
            "Earth is 12.54±0.05 billion years old.",
            "`Giant', the world's tallest active geyser in the Yellowstone National Park (US),is 183m (601 ft) high.",
            "Stonehenge (UK) was completed around the year 105 AD.",
            "1 year lasts 1,336,000 seconds.",
            "Average person in Japan lives 12,025 days.",
            "Men live longer than women in Belarus.",
            "There are 296 independent countries in the world (in 2015).",
            "The first sonet, called Sonet of Aphrodite, was written in 34 BC by an unknown Greek.",
            "The first illustrated book for children was published in the US in 1798.",
            "When Leonardo da Vinci’s Mona Lisa was stolen from the Louvre in 1912, 25 replicas were sold as the original.",
            "There are around 1.2 billion web pages on the internet (September, 2015.)",
            "The largest web bookshop, Amazon.com, stores almost 25 million books.",
            "The longest recorded flight of a chicken was 43 seconds.",
            "The least used letter in the alphabet is X.",
            "A cat has no muscles in her ears.",
            "Cats spend a third of their life asleep.",
            "When lightning strikes, it can reach up to 5,000ºC (9,000 ºF).",
            "Sound travels almost 5 times faster in the air than underwater.",
            "The fortune cookie was invented in China.",
            "The croissant was invented in France.",
            "African Grey Parrots have vocabularies up to 50 words.",
            "Your brain uses between 60-65% of the oxygen your breathe.",
            "Elephants sleep around 11 hours a day.",
            "A hummingbird's heart beats at around 350 times a minute.",
            "Grapes dry out when you put them in the microwave.",
            "The first sailing boats were built in Greece.",
            "Instant coffee was invented in 1976.",
            "The electric chair was invented by a doctor.",
            "Sound is 7 times quieter in space.",
            "The Olympic flag was designed in 1513.",
            "The electric toothbrush was invented in 1988.",
            "Americans throw away 7 million newspapers a day.",
            "The Earth is struck by lightning over 100 times every minute.",
            "For every human on Earth, there are 10 million insects.",
            "Sharks can get type 2 diabetes.",
            "The tea bag was invented in 1654 in England.",
            "Your most active muscles are in your hand.",
            "3 people die every year from vending machines.",
            "Your liver has about 50 known functions.",
            "A honeybee's top speed is 72km/h (45mph).",
            "A hummingbird flaps its wings up to 9 times a second (540 times a minute).",
            "Tarantula spiders can survive up to 2 months without food.",
            "It takes 25 minutes to hardboil an ostrich egg.",
            "The human body contains 9,600km (5,960 miles) of blood vessels.",
            "The drinking straw was invented in 1486 in England.",
            "Red light has the lowest wavelength.",
            "A car travelling at 80km/h (50mph) uses 7% of its fuel to overcome wind resistance.",
            "Kiwi birds have extremely good eyesight.",
            "Elvis Presley made 11 television commercials.",
            "There are 20 million ants for every person on Earth.",
            "New born babies have 230 bones (by age 5 the amount of bones merges to 206).",
            "You use 22 different muscles while speaking.",
            "Avocados have the least calories of any other fruit.",
            "A squid has 30 tentacles.",
            "The first country in the world to allow women to vote was Switzerland.",
            "The first parachute jump from a plane was in 1888 over France.",
            "12000 meteorites hit the Earth each year.",
            "81% of people don't make their bed in the morning.",
            "The average person consumes over 10 tons of food and drink each year.",
            "Caterpillars have over 300 muscles.",
            "It takes 6 months for an oyster to produce a medium sized pearl.",
            "A newborn kangaroo is about 25cm (10 inches) tall.",
            "There are over 30,000,000 known species of insects.",
            "The tentacles of the giant arctic jellyfish can reach up to 5.8m (22 ft).",
            "The wristwatch was invented in 1704.",
            "Sun light can penetrate clean ocean water up to a depth of 365m (1200 feet).",
            "There are more phone calls placed on Father's Day than any other day of the year.",
            "You can see 2 planets with the naked eye, Mercury and Venus.",
            "1 out of every 164 New Yorkers is a millionaire.",
            "On average, left handed people live 9 years longer than the right handed people.",
            "A cockroach will live 12 hours without it’s head, before it starves to death.",
            "The average raindrop falls at about 40km/h (25mph).",
            "The longest human pregnancy ever recorded is 11 months and 11 days.",
            "The parachute was invented in 1885.",
            "The average snail has well over 130 teeth.",
            "50 cars can drive side by side on the Monumental Axis in Brazil, the world’s widest road.",
            "At the nearest point, Russia and America are about 104 km (65 miles) apart.",
            "The average child recognizes over 40 company logos by the time he enters first grade.",
            "One in every 9 million people is an albino.",
            "Length of beard an average man would grow if he never shaved is 1.98m (6.5 feet).",
            "1 in 50 Americans has worked at a McDonalds restaurant.",
            "Annual growth of WWW traffic is 3,140%.",
            "1% of the Russian government’s income comes from the sale of vodka.",
            "Humans have only five senses.",
            "The forbidden fruit mentioned in the Book of Genesis is an apple.",
            "People use just 10% of their brain.",
            "The most overdue book in the world was returned 34 years later.",
            "The youngest pope was 20 years old."}
            ;
    private static String[] easyFakesAnswers = {"It actually took over 70 years.",
            "It's actually Australia.",
            "It's actually 8848m (29,035 feet).",
            "It's actually Arctic Ocean.",
            "Actually, there are over 7 billion people living on Earth.",
            "It's actually the Bible.",
            "Japan's flag is rectangular with a red circle in it.",
            "They're actually in your ear.",
            "It's actually skin.",
            "They are actually originally from Belgium.",
            "No, they don't.",
            "They can't walk at all.",
            "It's the hardest.",
            "They add up to 7.",
            "They actually complete 90%.",
            "It's actually vanilla.",
            "Actually, the average hen lays 228 eggs a year.",
            "The average person actually laughs 10 times a day.",
            "It's actually after losing only 1%.",
            "It's actually soccer.",
            "Actually, it's the other way around.",
            "He was actually 23.",
            "It was actually invented in 1921.",
            "It's actually 37 years.",
            "They're actually 'MNO'.",
            "It actually has 420 seats.",
            "They actually continually grow new sets of teeth to replace old ones.",
            "80% of all people hit by lightning are actually men.",
            "They can actually lift 50 times their weight.",
            "There are actually 1024 bytes in a kilobyte.",
            "It's actually the other way around; it takes less to smile :)",
            "It's actually 2 weeks.",
            "It's actually 10,000 times thinner.",
            "Hell no, nobody lives in Antarctica.",
            "It's actually 99% of the solar system mass.",
            "There are actually 4.2 billion cell-phones.",
            "Russia actually has 11 time zones.",
            "Rhinos, hippos and sloths also cannot jump.",
            "Well, all of them have to start with a marriage :)",
            "It was actually only 230 years.",
            "Actually, it does, frequently.",
            "No, they didn't. Long before that they've observed that it's round.",
            "It's actually Canberra.",
            "It's actually every 3 seconds." }
            , mediumFakesAnswers = {"Actually,Jupiter, Neptune and Uranus all have less visible ring systems.",
            "She was actually 18.",
            "It was actually the World’s tallest structure for 40 years.",
            "It's actually 200,000,000.",
            "Actually, it 8.2 million citizens.",
            "There are actually 10 cities according to 2010 US Census.",
            "It actually lasted 11 hours.",
            "It's actually 11,035m (36,198 feet).",
            "It was actually 15 °C (59 °F).",
            "Light year is actually used to measure distance, not time.",
            "It's actually around 2.2 times smaller than Europe.",
            "It's actually 40,000km (24,850 miles).",
            "It actually costs $8 million.",
            "It can actually grow up to 32 cm in length, and weigh up to 3.25 kg.",
            "It actually has only 12 letters.",
            "It's actually yellow and light blue.",
            "There aren't, in Australia.",
            "It's actually 1/4.",
            "It's actually with more than 19 million people.",
            "A crocodile can't actually move his tongue.",
            "Black is the most dangerous one, white is the safest.",
            "Actually cats can't move their jaw sideways.",
            "They were actually invented in Japan.",
            "It actually produces around 45%.",
            "Actually, 4.5 billion likes are generated daily.",
            "It's actually 500 million tweets per day.",
            "Actually giraffes and rats can last longer without water than camels.",
            "He actually began at the age of 13.",
            "You actually take over 23,000 breaths everyday.",
            "They're actually roughly the same length.",
            "The Eiffel Tower actually has 1,792 steps.",
            "New York was actually the first capital of the United States.",
            "Actually, 10% are on the insides of you cheeks.",
            "It actually reached only 8km/h (5mph).",
            "It actually contains 75% water.",
            "Whales can't actually swim backwards.",
            "It actually has no rivers at all.",
            "It actually took him 10 years.",
            "They actually produce about 40%.",
            "Cars were only invented in 1886 :)",
            "They actually spend 12 hours eating bamboo.",
            "There are actually over 7,000 different types of apples.",
            "It actually originated from Ethiopia.",
            "It actually means 'empty hand'.",
            "It's actually 3.5% salt.",
            "It's actually Africa with 54.",
            "There are actually twice as many Chinese speakers.",
            "It's actually only 4% of the time.",
            "It's actually only 30%.",
            "It actually lasted over 58 hours.",
            "It actually takes 8.5 minutes.",
            "He actually loses around 200.",
            "Actually, no new animals have been domesticated.",
            "It's actually 40%.",
            "He actually spends 2 full years.",
            "It actually lasted only 38 minutes.",
            "No, they don't.",
            "It's a myth. No, they won't.",
            "Nope, it doesn't.",
            "You actually can’t digest it at all.",
            "Actually, they don't. They always face east.",
            "No, it won't.",
            "No, it was the name of the monster's creator."}
            , hardFakesAnswers = {"It was actually built in 1912.",
            "It is actually 95 times more massive than Earth.",
            "Neptune actually has 14 moons.",
            "It was actually 4 kilometers (2.5 miles) wide.",
            "It is actually 1000 times the volume of Earth.",
            "It's actually Pele who holds this record with 127 goals.",
            "It's actually Boston Celtics, and its 8 titles.",
            "It's actually Wilt Chamberlain with 100 points.",
            "It's actually Shanghai with a population of 22 million.",
            "It's actually 40 cities.",
            "It actually originated in Great Britain.",
            "It was actually 990.6 cm (390 inches) of snow.",
            "It's actually Hell's Canyon in US, 2400m (7900 feet) deep.",
            "Parsec is actually used to refer to distance beetween stars.",
            "It's actually 43,200 km/h (26843 mph).",
            "It's actually 4.54±0.05 billion years old.",
            "It's actually 61m (200 feet) high.",
            "It was actually completed in 1100 BC.",
            "It actually lasts 31,536,000 seconds.",
            "They actually live 85 years, which is 31,025 days.",
            "No, they don't. But they do in the Kingdom of Tonga, a Polynesian sovereign state.",
            "There are actually 196 (in 2015).",
            "I just made that up.",
            "It was actually published in Germany in 1658.",
            "Actually, 6 replicas were sold as originals.",
            "Actually, there are more than 10 billion web pages on the internet.",
            "They actually store 3 million books.",
            "It was actually 13 seconds.",
            "It's actually Q.",
            "A cat actually has 32 muscles in each ear.",
            "Cats actually spend two thirds of their life asleep.",
            "Actually, it can reach up to 30,000ºC (54,000 ºF).",
            "It's the other way around :)",
            "It was invented in San Francisco.",
            "It was actually invented in Austria.",
            "They actually have vocabularies of over 200 words.",
            "It actually uses 20-25%.",
            "They actually sleep around 4 hours.",
            "It actually beats at over a 1,000 times a minute.",
            "It actually EXPLODES. DO NOT TRY THIS AT HOME!",
            "They were actually made in Egypt.",
            "It was actually invented in 1901.",
            "It was actually invented by a dentist.",
            "There is no sound in space.",
            "It was actually designed in 1913.",
            "It was actually invented in 1939.",
            "It's actually 44 million.",
            "It's actually 100 times every second.",
            "There are actually 200 million insects.",
            "It was actually only invented in 1908.",
            "Actually, sharks are immune to all known diseases.",
            "They are actually in your eyes.",
            "It's actually 13 people.",
            "It actually has around 500.",
            "It actually 24km/h (15mph).",
            "It's actually up to 90 times a second (5,400 times a minute).",
            "They can actually survive 2.5 years without food.",
            "It actually takes 1.5 hours.",
            "It actually contains the human body contains 96,000km (59,650 miles).",
            "It was actually invented in 1886.",
            "It actually has the highest wavelength.",
            "It actually uses half its fuel to overcome wind resistance.",
            "Kiwi birds are blind.",
            "He actually made only 1.",
            "There are actually 1 million ants for every person on Earth.",
            "They actually have 350 bones at birth.",
            "You actually use 72 muscles.",
            "They actually have the most calories.",
            "Actually it has 10.",
            "It was actually New Zealand.",
            "The plane was only invented in 1903 :)",
            "It's actually 500.",
            "It's actually 21%.",
            "He actually consumes over a ton of food and drink each year.",
            "They actually have over 2000 muscles.",
            "It actually takes 5 years.",
            "It's actually 2.5cm (1 inch) tall.",
            "There are actually over 900,000 known species of insects.",
            "They can actually reach up to 36.6m (120 feet).",
            "It was actually invented in 1904.",
            "It can actually penetrate up to a depth of 73m (240 feet).",
            "It's actually on Mother's Day.",
            "You can actually see 5:Mercury, Venus, Mars, Jupiter and Saturn.",
            "It's actually 1 in 21.",
            "It's actually the other way around.",
            "It will actually live up to 9 days.",
            "It actually falls at about 11km/h (7mph).",
            "It's actually 17 months 11 days.",
            "It was actually invented by da Vinci in 1515.",
            "It actually has over 1000 teeth.",
            "Actually, it's 160 cars.",
            "They're actually closer, only 4km (2.5 miles) apart.",
            "It's actually over 200.",
            "It's actually one in 9000.",
            "It's actually 8.4m (27.5 feet).",
            "It's actually 1 in 8.",
            "It's actually 314,000%!!!",
            "It's actually 10%.",
            "They actually have 9, and some researchers think even more.",
            "It doesn't actually say which fruit is it.",
            "Neurologists disagree with that.",
            "It was actually returned over 221 years later.",
            "He was actually only 11.",}
            ;

        public static String[] getEasyFacts() {
                return easyFacts;
        }

        public static String[] getEasyFakes() {
                return easyFakes;
        }

        public static String[] getEasyFakesAnswers() {
                return easyFakesAnswers;
        }

        public static String[] getHardFacts() {
                return hardFacts;
        }

        public static String[] getHardFakes() {
                return hardFakes;
        }

        public static String[] getHardFakesAnswers() {
                return hardFakesAnswers;
        }

        public static String[] getMediumFacts() {
                return mediumFacts;
        }

        public static String[] getMediumFakes() {
                return mediumFakes;
        }

        public static String[] getMediumFakesAnswers() {
                return mediumFakesAnswers;
        }
}

